language: node_js
node_js:
- 10.13
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
    - secure: DkgD8m0GhZbUR2aaeZGRK8cqBbKFHSzzRK7txNNsqEQRx/+32BIOIYKj3WqdFawWMKJEsf4IG7SWawQD3x8QMA88EsvbikVvWLkmL++XhfPKq5js5sm4LO7HdltKvfiorL4HsvRTsVzjdY/EuSFv0tx76+29I7SQL0scWriE56frRrzUOs2Txvu/QUSJu+l37TakvnKvF/KessgqgPnO2jCj7EadOYsYJlIPRow1TjHIFen2Neab8ahn1vl02GU/da0r9EWjkjhV7mU3aNkHz/jZieJ8KEBU9ocAcXH1pLeQNl8/qn7h6vZ5xOJzQujzkvYZ2H4rzFFVh6mJwtiwn1nItQ82qIELF4lVQ0vJM41loHfqVxEt/eCsPlNu+R4kb7bAu8AVSg8q7rOiIExia1CQeOkYE8UX9L6achI7Jt7AXfMvteunc2oqMtcJVDVL8LUyJ+mLKsCXoI8TBGDOIOlpo/K+tL39+uLPe+N2t1RM7RtEfpGhgcj8H2LcPH6REhqxmkc61wZ/yklnGEIZRtyI3Ca2YL4Iv+4CR6/5rQdovlBC63Cb02Zghpb74Ywt7eXodltochLy8YaWGD9cHKhCquDkMdfRpzBic50aOXsA5ey+jfhTPBsjYFqyrtu9rOvNrxV1fIpNgDtIaOlReL+y1YtUC6FcDNM0W4auqEc=
    on_pull_requests: false
    on_failure: never
install:
- npm install
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- npm prune
- greenkeeper-lockfile-update
after_success:
- npm run coveralls
- npm run semantic-release
after_script:
- greenkeeper-lockfile-upload
